name: release

on:
   workflow_dispatch:
      inputs:
         version:
            description: "The release version"
            required: true
            default: "3.0."
         branch:
            description: "The branch to release from"
            required: true
            default: 'master'

jobs:
   publish:
      runs-on: ubuntu-latest

      steps:
         -  uses: actions/checkout@v3
            with:
               fetch-depth: 0
               ref: ${{ github.event.inputs.branch }}

         -  uses: actions/setup-java@v3
            with:
               distribution: "temurin"
               java-version: "17"

         -  name: publish multiplatform release
            run: ./gradlew publishKotlinMultiplatformPublicationToDeployRepository

         -  name: publish jvm release
            run: ./gradlew publishJvmPublicationToDeployRepository

         -  name: publish js release
            run: ./gradlew publishJsPublicationToDeployRepository

env:
   GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
   RELEASE_VERSION: ${{ github.event.inputs.version }}
   OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
   OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
   ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
   ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
